apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  serviceName: radarr-svc
  replicas: 1
  template:
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:4.5.2
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        ports:
        - containerPort: 7878
          name: web
        volumeMounts:
        - name: config
          mountPath: /config
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
