apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dvr
commonLabels:
  app: anime-sonarr
resources:
  - ../../base
  - ingress.yaml
namePrefix: anime-
patches:
  - path: statefulset_patch.yaml
    target:
      kind: StatefulSet
      name: sonarr