apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  serviceName: sonarr-svc
  replicas: 1
  template:
    spec:
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:1.6.3
        ports:
        - containerPort: 9696
          name: web
        volumeMounts:
        - name: config
          mountPath: /config
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
