apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dvr
resources:
  - ../../base
  - ingress.yaml
patches:
  - path: statefulset_patch.yaml
    target:
      kind: StatefulSet
      name: sonarr