apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blocky-system
namePrefix: prod-
resources:
  - ../../base
configMapGenerator:
  - name: blocky-config
    files:
      - config.yaml
patches:
  - target:
      version: v1
      kind: Service
      name: blocky-svc
    path: service-patch.yaml